version: 2.1
orbs: 
    node: circleci/node@5.0.0
    browser-tools: circleci/browser-tools@1.3.0

jobs:
    unit-test:
        docker:
            - image: cimg/node:lts-browsers
        steps:
            - checkout
            - node/install-packages:
                pkg-manager: yarn-berry
            - browser-tools/install-chrome
            - browser-tools/install-chromedriver
            - run:
                name: Unit test
                command: yarn test:ci
    lint:
        docker:
            - image: cimg/node:lts-browsers
        steps:
            - checkout
            - node/install-packages:
                pkg-manager: yarn
            - run:
                name: Lint
                command: yarn lint

workflows:
    sample:
        jobs:
            - lint
            - unit-test
