version: 2.1
var_1: &cache_key ng-cad2-{{ .Branch }}-{{ checksum "yarn.lock" }}
var_2: &cache_fallback_key ng-cad2
var_3: &restore_cache
  restore_cache:
    keys:
      - *cache_key
      - *cache_fallback_key
var_4: &save_cache
    save_cache:
        key: *cache_key
        paths:
        - "node_modules"
executors:
    ng-cad2:
        working_directory: ~/ng-cad2
        docker:
            - image: circleci/node:10-browsers
jobs:
    build:
        executor: ng-cad2
        steps:
            - checkout
            - *restore_cache
            - run:
                  name: Install local dependencies
                  command: yarn install
            - *save_cache
    test:
        executor: ng-cad2
        steps:
            - checkout
            - *restore_cache
            - run:
                  name: Unit test
                  command: yarn test --no-watch --no-progress --browsers=ChromeHeadless
            - run:
                  name: End to end test
                  command: yarn e2e --protractor-config=e2e/protractor.conf.js
    lint:
        executor: ng-cad2
        steps:
            - checkout
            - *restore_cache
            - run:
                  name: Lint
                  command: yarn lint
workflows:
    build-test-lint:
        jobs:
            - build
            - test:
                  requires:
                      - build
            - lint:
                  requires:
                      - build
