version: 2.1
var_1: &cache_key ng-cad2-{{ .Branch }}-{{ checksum "package-lock.json" }}
var_2: &cache_fallback_key ng-cad2
var_3: &restore_cache
    restore_cache:
        keys:
            - *cache_key
            - *cache_fallback_key
var_4: &save_cache
    save_cache:
        key: *cache_key
        paths:
            - "node_modules"
executors:
    ng-cad2:
        working_directory: ~/ng-cad2
        docker:
            - image: circleci/node:16-browsers
jobs:
    build:
        executor: ng-cad2
        steps:
            - checkout
            - *restore_cache
            # - run: git submodule update --init --recursive
            - run:
                  name: Install local dependencies
                  command: npm install
            - *save_cache
    unit-test:
        executor: ng-cad2
        steps:
            - checkout
            - *restore_cache
            - run: git submodule update --init --recursive
            - run:
                  name: Install utils dependencies
                  command: cd ./src/cad-viewer/src/utils && npm install
            - run:
                  name: Install cad-viewer dependencies
                  command: cd ./src/cad-viewer && npm install
            - run:
                  name: Unit test
                  command: npm run test:ci
    e2e:
        executor: ng-cad2
        steps:
            - checkout
            - *restore_cache
            - run:
                  name: End to end
                  command: npm run e2e -- --protractor-config=e2e/protractor.conf.js
    lint:
        executor: ng-cad2
        steps:
            - checkout
            - *restore_cache
            - run:
                  name: Lint
                  command: npm run lint
workflows:
    build-test-lint:
        jobs:
            - build
            - unit-test:
                  requires:
                      - build
            # - e2e:
            #       requires:
            #           - build
            - lint:
                  requires:
                      - build
